### ISSUE TITLE
Add support for Mobile pairing in case of standalone app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-dao-governance-app#3]
In our mobile app, it's possible to generate a key (EOA). 
Connect using Mobile pairing allows connecting such generated EOA to our interface 

It might be beneficial for the users who generated key(EOA) in the mobile app to be able to use the connection to the standalone app using Safe Mobile pairing.

**Comment by liliya-soroka** [comment]
@johannesmoormann and @DmitryBespalov

**Comment by iamacook** [comment]
As we need to modify the pairing module for the forthcoming WalletConnect update, I would suggest we hold off on this until we [update `web-core` pairing](https://github.com/safe-global/web-core/issues/563).

**Comment by iamacook** [comment]
Taking into consideration the deprecation of mobile pairing, I will close this.
