### ISSUE TITLE
[Bug] Voting power sometimes doesn't update when switching between chains

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-dao-governance-app#4]
## Description

When switching between Görli and Mainnet, the voting power is sometimes not being updated in the UI.

Note: I think this is a minor bug because only test wallets should have any SAFE Tokens on Görli.

## Steps to reproduce

1. Open the governance app
2. Switch wallet to Görli with SAFE Tokens in it
3. Click the "Switch to Ethereum" Button at the top
4. Observe the number not updating sometimes

## Screenshot

Note: This wallet doesn't have any SAFE on mainnet, only on Görli

<img width="1107" alt="Screenshot 2023-02-27 at 16 34 14" src="https://user-images.githubusercontent.com/5880855/221607749-19d3f497-b292-4a82-a05d-0b8f7dc49552.png">

**Comment by iamacook** [comment]
As this only affects us, we agreed to close this for now and revisit it if we ever enable more than one chain.
